import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:go_router/go_router.dart';

class SplashScreen extends StatefulWidget { const SplashScreen({super.key}); @override State<SplashScreen> createState()=>_SplashScreenState(); }
class _SplashScreenState extends State<SplashScreen> {
  @override void initState(){super.initState();_bootstrap();}
  Future<void> _bootstrap() async { await Future<void>.delayed(const Duration(milliseconds:1400)); if(!mounted)return; final user=FirebaseAuth.instance.currentUser; if(user==null){context.go('/onboarding');return;} await user.reload(); final refreshed=FirebaseAuth.instance.currentUser; if(!mounted)return; if(refreshed==null){context.go('/login');} else if(!refreshed.emailVerified){context.go('/verify-email');} else {context.go('/dashboard');} }
  @override Widget build(BuildContext context)=>Scaffold(body:Stack(fit:StackFit.expand,children:[Image.asset('assets/images/splash_bg.jpg',fit:BoxFit.cover,errorBuilder:(c,e,s)=>Image.asset('assets/images/stadium.jpg',fit:BoxFit.cover)),Container(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Colors.black.withOpacity(.22),Colors.black.withOpacity(.82)]))),SafeArea(child:Center(child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Container(width:112,height:112,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white.withOpacity(.12),borderRadius:BorderRadius.circular(32),border:Border.all(color:Colors.white24)),child:SvgPicture.asset('assets/icons/football_badge.svg')),const SizedBox(height:28),const Text('CROC CITY',style:TextStyle(color:Colors.white,fontSize:38,fontWeight:FontWeight.w900,letterSpacing:2.4)),const Text('FOOTBALL ACADEMY',style:TextStyle(color:Color(0xFFF4B400),fontSize:16,fontWeight:FontWeight.w800,letterSpacing:2.2)),const SizedBox(height:16),const Text('Developing Talent • Building Character • Creating Champions',textAlign:TextAlign.center,style:TextStyle(color:Colors.white70,fontSize:14,height:1.45)),const SizedBox(height:44),const SizedBox(width:28,height:28,child:CircularProgressIndicator(strokeWidth:2.5,color:Colors.white))]))))]));
}
