// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHPf-khzfnIRivzK1_o7OjZH0N63Ek2zI',
    appId: '1:603627312930:web:98cada718581bdd378377b',
    messagingSenderId: '603627312930',
    projectId: 'croc-city-football-academy',
    authDomain: 'croc-city-football-academy.firebaseapp.com',
    storageBucket: 'croc-city-football-academy.firebasestorage.app',
    measurementId: 'G-W7WDC6VD0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlypsvuQw35gydL6S83vvAX6cC272A7WA',
    appId: '1:603627312930:android:c625d9437bf7214f78377b',
    messagingSenderId: '603627312930',
    projectId: 'croc-city-football-academy',
    storageBucket: 'croc-city-football-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKHfV8TFAXXb-yoJ1sRw0GNu6XATOks8Q',
    appId: '1:603627312930:ios:2cd803363d0e8ce278377b',
    messagingSenderId: '603627312930',
    projectId: 'croc-city-football-academy',
    storageBucket: 'croc-city-football-academy.firebasestorage.app',
    iosBundleId: 'com.example.crocCityFootballAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKHfV8TFAXXb-yoJ1sRw0GNu6XATOks8Q',
    appId: '1:603627312930:ios:2cd803363d0e8ce278377b',
    messagingSenderId: '603627312930',
    projectId: 'croc-city-football-academy',
    storageBucket: 'croc-city-football-academy.firebasestorage.app',
    iosBundleId: 'com.example.crocCityFootballAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHPf-khzfnIRivzK1_o7OjZH0N63Ek2zI',
    appId: '1:603627312930:web:acff3bda06617fba78377b',
    messagingSenderId: '603627312930',
    projectId: 'croc-city-football-academy',
    authDomain: 'croc-city-football-academy.firebaseapp.com',
    storageBucket: 'croc-city-football-academy.firebasestorage.app',
    measurementId: 'G-BS3L9RFFWV',
  );
}
